/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Category.FGModuleCat.EssentiallySmall
public import TauCeti.CategoryTheory.Action.EssentiallySmall
public import TauCeti.CategoryTheory.GrothendieckGroup.Monoidal
public import TauCeti.RepresentationTheory.CharacterTable.VirtualCharacter

/-!
# The representation ring and its character homomorphism

The **representation ring** `R(G)` of a monoid `G` over a commutative Noetherian ring `R` is the
*split* Grothendieck ring of the module-finite representations `FDRep R G`: its underlying
additive group is generated by the classes `[V]` of objects subject only to `[V ⊕ W] = [V] + [W]`,
and its multiplication is induced by the tensor product, so that `[V] · [W] = [V ⊗ W]` with unit
the class of the trivial rank-one representation. The character homomorphism built on top of it is
a statement about a field, characters being available only there.

*Split* is meant literally, and it is in general a restriction: the relations imposed are those of
the direct sums, not those of all short exact sequences, so what is built here is the ring also
known as the **Green ring** of `G` over `R`, and not in general the Grothendieck ring of the
abelian category `FDRep R G`. The two coincide exactly when every short exact sequence of
module-finite representations splits — for a finite *group* `G` whose order is invertible in `R`
that is Maschke's theorem, while for a general monoid, or in modular characteristic, they can
differ. Everything below is a statement about the split ring.

Both structures are already available: `TauCeti.SplitK0` is exactly the group presented by the
biproduct relations, and `TauCeti.SplitK0.instCommRing` puts the tensor multiplication on it for
any braided monoidal additive category. What was missing is that `FDRep R G` satisfies the
smallness hypothesis those constructions ask for, which
`TauCeti/CategoryTheory/Action/EssentiallySmall.lean` supplies, so `TauCeti.repRing` here is a
name for `TauCeti.SplitK0 (FDRep R G)` rather than a second construction; every lemma about split
`K₀` applies to it verbatim.

On top of that this file builds the **character homomorphism** `TauCeti.repRingCharacter`, the
ring homomorphism `R(G) → (G → k)` sending `[V]` to `FDRep.character V`. That the character
descends to `R(G)` at all is the conjunction of three facts about it: it is an isomorphism
invariant (`FDRep.char_iso`), it is additive on biproducts (`FDRep.char_biprod`), and it is
multiplicative on tensor products (`FDRep.char_tensor`), the unit going to the constant function
`1` (`FDRep.char_tensorUnit`). Its image is described exactly: it is the virtual-character lattice
`TauCeti.virtualCharacters`, and in particular, when `G` is a group, so that conjugation and hence
the class functions make sense, every value is a class function.

Note what is *not* claimed. For a **finite group** `G` over an algebraically closed field of
characteristic zero the character homomorphism is injective — that is the statement that a virtual
representation is determined by its character — but that rests on the freeness of `R(G)` on the
isomorphism classes of irreducible representations, which for the split ring comes from Maschke's
theorem: it is semisimplicity, not a Jordan-Hölder filtration, that decomposes every object of
`FDRep k G` into a direct sum of irreducibles and so makes the biproduct relations the only ones.
Neither that decomposition nor the injectivity is proved here, and outside the finite semisimple
regime — for a monoid, or in modular characteristic — injectivity is not to be expected at all.

## Main definitions

* `TauCeti.repRing`: the representation ring `R(G)`.
* `TauCeti.repRingCharacter`: the character homomorphism `R(G) →+* (G → k)`.

## Main statements

* `TauCeti.repRingCharacter_of`: the character homomorphism sends the class of a representation to
  its character; `TauCeti.SplitK0.ringHom_ext` then makes it the only ring homomorphism that does.
* `TauCeti.repRingCharacter_mem_virtualCharacters` and `TauCeti.range_repRingCharacter`: **its
  image is the virtual-character lattice**.
* `TauCeti.repRingCharacter_mem_classFunction`: for a group `G`, every value of the character
  homomorphism is a class function.

## References

This builds the objects pinned as `repRing`, `repRingCharacter`,
`repRingCharacter_mem_classFunction` in Layer 4b of
`TauCetiRoadmap/RepresentationTheory/CharacterTheory/Suggested.lean` ("the representation ring"),
which is also the first bullet of Layer 6 of
`TauCetiRoadmap/RepresentationTheory/InductionRestriction/README.md` ("the representation ring and
its character map").
-/

public section

open CategoryTheory

universe u v

namespace TauCeti

section Monoid

variable {k : Type u} {G : Type v} [Field k] [Monoid G]

/-- **The representation ring** `R(G)` of a monoid `G` over a commutative ring `R`: the split
Grothendieck ring of `FDRep R G`, with addition induced by the direct sum and multiplication by
the tensor product.

It is a name for the split Grothendieck group of `FDRep R G`, whose ring structure
`TauCeti.SplitK0.instCommRing` already supplies, so that `TauCeti.SplitK0.of` is the class map,
`TauCeti.SplitK0.of_mul_of` the computation rule `[V] · [W] = [V ⊗ W]`, and
`TauCeti.SplitK0.induction_on` the induction principle. Splitting the classes only along
biproducts is deliberate: `FDRep R G` is abelian, so one could instead impose the relation of
every short exact sequence, but the representation ring is the one where `[V] = [V'] + [V'']`
holds for a *split* extension. The two presentations agree for a finite **group** `G` whose order
is invertible in `R`, every short exact sequence of representations then splitting by Maschke's
theorem; for a general monoid `G`, or in modular characteristic, they can differ and this is the
split one, the Green ring of `G` over `R`.

The coefficients are a commutative ring, not just a field: nothing in the split ring needs
division. `IsNoetherianRing R` is what makes `FDRep R G` an additive category with biproducts at
all — Mathlib gates the abelian structure of `FGModuleCat R`, hence the finite limits it is built
from, on that hypothesis (`Mathlib/Algebra/Category/FGModuleCat/Limits.lean`) — and a field
supplies both. -/
abbrev repRing (R : Type u) (G : Type v) [CommRing R] [IsNoetherianRing R] [Monoid G] :
    Type (max u v) :=
  SplitK0.{max u v} (FDRep R G)

/-- **The character as an invariant of the representation ring.** The three fields are the three
functoriality properties of `FDRep.character`: it is defined on objects, it does not change under
an isomorphism (`FDRep.char_iso`), and it is additive on biproducts (`FDRep.char_biprod`).

This is only the construction datum of `TauCeti.repRingCharacter`, whose characteristic property
`TauCeti.repRingCharacter_of` is the intended interface, so it is not part of the public API. -/
private noncomputable def characterInvariant (k : Type u) (G : Type v) [Field k] [Monoid G] :
    SplitK0.AdditiveInvariant (FDRep k G) (G → k) where
  obj V := V.character
  map_iso _ _ i := FDRep.char_iso i
  map_biprod := FDRep.char_biprod

/-- **The character homomorphism of the representation ring**: the ring homomorphism
`R(G) →+* (G → k)` sending the class of a representation to its character.

It is a homomorphism of *rings*, not merely of groups, because the character is multiplicative
under the tensor product (`FDRep.char_tensor`) and takes the tensor unit to the constant function
`1` (`FDRep.char_tensorUnit`). -/
noncomputable def repRingCharacter (k : Type u) (G : Type v) [Field k] [Monoid G] :
    repRing k G →+* (G → k) :=
  SplitK0.liftRingHom (characterInvariant k G) (FDRep.char_tensorUnit k G) FDRep.char_tensor

/-- The character homomorphism sends the class of a representation to its character. -/
@[simp]
theorem repRingCharacter_of (V : FDRep k G) :
    repRingCharacter k G (SplitK0.of V) = V.character :=
  SplitK0.liftRingHom_of _ _ _ V

/-- Every value of the character homomorphism is a virtual character: the classes of objects
generate `R(G)`, and the virtual characters are an additive subgroup containing every character. -/
@[simp]
theorem repRingCharacter_mem_virtualCharacters (x : repRing k G) :
    repRingCharacter k G x ∈ virtualCharacters k G := by
  induction x using SplitK0.induction_on with
  | zero => simp only [map_zero]; exact zero_mem _
  | of V => simp only [repRingCharacter_of]; exact character_mem_virtualCharacters V
  | add a b ha hb => simp only [map_add]; exact add_mem ha hb
  | neg a ha => simp only [map_neg]; exact neg_mem ha

/-- **The image of the character homomorphism is the virtual-character lattice.** Both sides are
the additive subgroup generated by the characters: the left because the classes of objects
generate `R(G)` (`TauCeti.SplitK0.closure_range_of`), the right by definition. -/
@[simp]
theorem range_repRingCharacter (k : Type u) (G : Type v) [Field k] [Monoid G] :
    (repRingCharacter k G : repRing k G →+ (G → k)).range = virtualCharacters k G :=
  le_antisymm (by rintro _ ⟨x, rfl⟩; exact repRingCharacter_mem_virtualCharacters x)
    (virtualCharacters_le fun V => ⟨SplitK0.of V, repRingCharacter_of V⟩)

end Monoid

section Group

variable {k : Type u} {G : Type v} [Field k] [Group G]

/-- **Every value of the character homomorphism is a class function.** A character is constant on
conjugacy classes, and the class functions form an additive subgroup, so the whole image is
contained in them; this is `TauCeti.virtualCharacters_le_classFunction` read through
`TauCeti.range_repRingCharacter`. -/
theorem repRingCharacter_mem_classFunction (x : repRing k G) :
    repRingCharacter k G x ∈ ClassFunction k G :=
  virtualCharacters_le_classFunction (repRingCharacter_mem_virtualCharacters x)

end Group

end TauCeti
